### PR TITLE
feat: parse and re-use admin token username

### PR DESCRIPTION
**Pull request by TJM**
This will parse the username from the current token and re use it for the new one during rotation.

It will default to "admin" if the subject parsing doesn't work.

### CODE REVIEW

**Review by alexhung — APPROVED** [review]
LGTM. This reminds me that we need to add more tests 😄

**Comment by TJM** [comment]
I did test this against our Artifactory 7.38 instance here. For all that is worth. Automated tests would be a "good thing" (tm)

**Review by shrajfr12 — APPROVED** [review]
lgtm

**Comment by TJM** [comment]
This allows you to name your access token something reasonable like `vault-artifactory-admin` ... I am not sure which version of artifactory required the username to specifically be `admin`, but on a reasonably recent version, that is no longer the case, and can make debugging issues much easier.

**Comment by alexhung** [comment]
@TJM Don't quote me on this, but I think it's the switch to scoped token that remove the restriction of `admin` username. However, this doesn't mean you can use *any* username as it still needs to match with a valid username in Artifactory.

**Review by Turhsus — APPROVED** [review]
LGTM, nice catch

**Pull request merged**
